# Generated by Django 6.0.4 on 2026-04-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpu_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='cpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
