# Generated by Django 6.0.4 on 2026-04-27 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_device_cpu_temp_device_cpu_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='cpu_temp',
        ),
        migrations.RemoveField(
            model_name='device',
            name='cpu_usage',
        ),
    ]
